# Generated by Django 5.0.2 on 2025-10-16 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_movil_escolar_api', '0002_administradores_delete_profiles'),
    ]

    operations = [
        migrations.AddField(
            model_name='administradores',
            name='clave_admin',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='administradores',
            name='edad',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='administradores',
            name='ocupacion',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='administradores',
            name='rfc',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='administradores',
            name='telefono',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
