# Generated by Django 5.0.2 on 2025-10-16 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_movil_escolar_api', '0003_administradores_clave_admin_administradores_edad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administradores',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
