# Generated by Django 5.0.2 on 2025-10-16 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_movil_escolar_api', '0005_alumnos_maestros'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alumnos',
            old_name='grado',
            new_name='curp',
        ),
        migrations.RenameField(
            model_name='alumnos',
            old_name='grupo',
            new_name='id_alumno',
        ),
        migrations.RenameField(
            model_name='alumnos',
            old_name='matricula',
            new_name='ocupacion',
        ),
        migrations.AddField(
            model_name='alumnos',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alumnos',
            name='rfc',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
